FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Freedcamp

Freedcamp

## Sessions Collection [/sessions]

### Sessions [GET]

+ Response 200 (application/json)

        [
            {
                "projects": [
      {
        "project_id": "914936",
        "role_name": "User",
        "role_type": "0",
        "project_name": "sdcscsdcscsdc",
        "project_description": "sdcsdcsdcsdcsdc",
        "project_color": "A86D54",
        "f_active": true,
        "f_can_delete": false,
        "f_can_manage": false,
        "f_can_leave": true,
        "notifications_count": 0,
        "users": [
          132942,
          309953,
          340312,
          377037,
          377039,
          377040
        ],
        "applications": [
                  6
            ]
        },
      "groups": [....],
      ...
   ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }